#ifndef __OUTPOINT_H
#define __OUTPOINT_H

#include "includes.h"

/**OUTPOINT**/
#define OUTPOINT_GPIO_RCC_1     RCC_APB2Periph_GPIOA
#define OUTPOINT_GPIO_RCC_2     RCC_APB2Periph_GPIOB
#define OUTPOINT_GPIO_RCC_3     RCC_APB2Periph_GPIOC
#define OUTPOINT_GPIO_RCC_4     RCC_APB2Periph_GPIOD

#define OUTPOINT_1_GPIO_PIN 	GPIO_Pin_13
#define OUTPOINT_1_GPIO_PORT  	GPIOB

#define OUTPOINT_2_GPIO_PIN 	GPIO_Pin_15
#define OUTPOINT_2_GPIO_PORT  	GPIOB

#define OUTPOINT_3_GPIO_PIN 	GPIO_Pin_7
#define OUTPOINT_3_GPIO_PORT  	GPIOC

#define OUTPOINT_4_GPIO_PIN 	GPIO_Pin_9
#define OUTPOINT_4_GPIO_PORT 	GPIOC

#define OUTPOINT_5_GPIO_PIN 	GPIO_Pin_9
#define OUTPOINT_5_GPIO_PORT  	GPIOA

#define OUTPOINT_6_GPIO_PIN 	GPIO_Pin_15
#define OUTPOINT_6_GPIO_PORT 	GPIOA

#define OUTPOINT_7_GPIO_PIN 	GPIO_Pin_11
#define OUTPOINT_7_GPIO_PORT  	GPIOC

#define OUTPOINT_8_GPIO_PIN 	GPIO_Pin_2
#define OUTPOINT_8_GPIO_PORT 	GPIOD

#define OUTPOINT_9_GPIO_PIN 	GPIO_Pin_4
#define OUTPOINT_9_GPIO_PORT 	GPIOB

#define OUTPOINT_10_GPIO_PIN 	GPIO_Pin_6
#define OUTPOINT_10_GPIO_PORT 	GPIOB

#define OUTPOINT_11_GPIO_PIN 	GPIO_Pin_8
#define OUTPOINT_11_GPIO_PORT  	GPIOB

#define OUTPOINT_12_GPIO_PIN 	GPIO_Pin_13
#define OUTPOINT_12_GPIO_PORT 	GPIOC

#define OUTPOINT_13_GPIO_PIN 	GPIO_Pin_15
#define OUTPOINT_13_GPIO_PORT  	GPIOC

#define OUTPOINT_14_GPIO_PIN 	GPIO_Pin_1
#define OUTPOINT_14_GPIO_PORT  	GPIOC

#define OUTPOINT_15_GPIO_PIN 	GPIO_Pin_3
#define OUTPOINT_15_GPIO_PORT 	GPIOC

#define OUTPOINT_16_GPIO_PIN 	GPIO_Pin_0
#define OUTPOINT_16_GPIO_PORT 	GPIOC

#define OUTPOINT_17_GPIO_PIN 	GPIO_Pin_2
#define OUTPOINT_17_GPIO_PORT 	GPIOC

#define OUTPOINT_18_GPIO_PIN 	GPIO_Pin_0
#define OUTPOINT_18_GPIO_PORT 	GPIOA

#define OUTPOINT_19_GPIO_PIN 	GPIO_Pin_7
#define OUTPOINT_19_GPIO_PORT 	GPIOB

#define OUTPOINT_20_GPIO_PIN 	GPIO_Pin_9
#define OUTPOINT_20_GPIO_PORT  	GPIOB

#define OUTPOINT_21_GPIO_PIN 	GPIO_Pin_14
#define OUTPOINT_21_GPIO_PORT  	GPIOC

#define OUTPOINT_22_GPIO_PIN 	GPIO_Pin_12
#define OUTPOINT_22_GPIO_PORT 	GPIOC

#define OUTPOINT_23_GPIO_PIN 	GPIO_Pin_3
#define OUTPOINT_23_GPIO_PORT  	GPIOB

#define OUTPOINT_24_GPIO_PIN 	GPIO_Pin_5
#define OUTPOINT_24_GPIO_PORT 	GPIOB

#define OUTPOINT_25_GPIO_PIN 	GPIO_Pin_8
#define OUTPOINT_25_GPIO_PORT 	GPIOA

#define OUTPOINT_26_GPIO_PIN 	GPIO_Pin_10
#define OUTPOINT_26_GPIO_PORT 	GPIOA

#define OUTPOINT_27_GPIO_PIN 	GPIO_Pin_10
#define OUTPOINT_27_GPIO_PORT 	GPIOC

#define OUTPOINT_28_GPIO_PIN	GPIO_Pin_14
#define OUTPOINT_28_GPIO_PORT 	GPIOB

#define OUTPOINT_29_GPIO_PIN 	GPIO_Pin_6
#define OUTPOINT_29_GPIO_PORT 	GPIOC

#define OUTPOINT_30_GPIO_PIN 	GPIO_Pin_8
#define OUTPOINT_30_GPIO_PORT  	GPIOC

#define OUTPOINT_31_GPIO_PIN 	GPIO_Pin_1
#define OUTPOINT_31_GPIO_PORT  	GPIOA

#define OUTPOINT_32_GPIO_PIN 	GPIO_Pin_2
#define OUTPOINT_32_GPIO_PORT	GPIOA

void OutPoint_Init(void);

#endif
